In [1]:
%autosave 5

Autosaving every 5 seconds


# Numpy

In [1]:
import numpy as np

### 1-D array (vector)

In [2]:
numbers = [2,3,6,5,4,7,8]
num_row = np.array(numbers)

In [3]:
print(numbers)
print(num_row)

[2, 3, 6, 5, 4, 7, 8]
[2 3 6 5 4 7 8]


In [4]:
numbers = [[1],
           [2],
           [3],
           [4],
           [5],
           [6]]
num_col = np.array(numbers)

In [5]:
print(numbers)
print(num_col)

[[1], [2], [3], [4], [5], [6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


### 2-D array (matrix)

In [6]:
numbers = [[1,2,3],
           [4,5,6],
           [7,8,9],
           [10,11,12]]

In [7]:
num_mat = np.array(numbers)

In [8]:
print(numbers)
print(num_mat)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### empty matrix

In [9]:
mt = np.empty((3,3))

In [10]:
print(mt)
print(mt.shape)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [4.22787460e-307 2.67019592e-306 1.42413555e-306]
 [1.78019082e-306 1.37959740e-306 2.29178686e-312]]
(3, 3)


### selection

In [11]:
vector = np.array([1,2,3,4,5,6,7,8])

In [12]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [13]:
vector[1] # select second element

2

In [14]:
matrix[1,1] # select second element in the second matrix
#00   01   02
#10   11   12
#20   21   22

5

### multi-selection

In [15]:
vector[:] # all vector

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
vector[:4] # select up to 3rd element  [:4] or [0:4]

array([1, 2, 3, 4])

In [17]:
vector[3:] # everything after 3rd element including 3rd

array([4, 5, 6, 7, 8])

In [18]:
vector[-1] # last element

8

In [19]:
matrix[::] # all matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
matrix[:2] # first two rows in matrix [:2] or [0:2] or [0:2:]

array([[1, 2, 3],
       [4, 5, 6]])

### describing matrices

In [21]:
matrix.shape # return dimensions

(3, 3)

In [22]:
matrix.ndim # return number of dimensions

2

In [23]:
matrix.size # return rows * columns

9

### max and min

In [24]:
np.max(matrix)

9

In [25]:
np.min(matrix)

1

In [26]:
np.max(matrix,axis=0) # max in each col

array([7, 8, 9])

In [27]:
np.max(matrix,axis=1) # max in each row

array([3, 6, 9])

### operations on vectors and matrices

In [28]:
def fun(x):
    if x > 4:
        return 0
    return 1

In [29]:
matrix_add = np.vectorize(fun)

In [30]:
matrix_add(matrix)

array([[1, 1, 1],
       [1, 0, 0],
       [0, 0, 0]])

In [31]:
matrix * 100 + 1

array([[101, 201, 301],
       [401, 501, 601],
       [701, 801, 901]])

### statistics

In [32]:
np.mean(matrix)

5.0

In [33]:
np.var(matrix)

6.666666666666667

In [34]:
np.std(matrix)

2.581988897471611

In [35]:
np.mean(matrix,axis=0) # mean in each col

array([4., 5., 6.])

### reshaping

In [43]:
mat = np.array([[1,2,3,4],
                [7,8,9,10],
                [12,13,14,15]])

In [44]:
mat.shape

(3, 4)

In [47]:
mat.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 9, 10],
       [12, 13],
       [14, 15]])

In [48]:
mat.size

12

In [49]:
mat.reshape(12)

array([ 1,  2,  3,  4,  7,  8,  9, 10, 12, 13, 14, 15])

### transpose

In [50]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [64]:
row = np.array([[1,2,3,4,5]]) # must turn 1-d array(vector) to 2-d array first 

In [65]:
row.T

array([[1],
       [2],
       [3],
       [4],
       [5]])

### flatten a matrix

In [66]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### diagonal

In [67]:
matrix.diagonal()

array([1, 5, 9])

### mathematical operations

In [76]:
A = np.array([1,2,3])
B = np.array([4,5,6])

In [79]:
dot = np.dot(A,B)

In [81]:
dot

32

In [82]:
add = np.add(A,B)

In [83]:
add

array([5, 7, 9])

In [84]:
sub = np.subtract(A,B)

In [85]:
sub

array([-3, -3, -3])

### generate random numbers

In [92]:
np.random.random(5) # 5 random float numbers

array([0.275958  , 0.96774166, 0.1040722 , 0.81562092, 0.84176579])

In [93]:
np.random.randint(0,10,5) # 5 random integers between 0 and 10

array([8, 4, 7, 7, 1])

In [94]:
np.random.uniform(1,5,3) # 3 random float numbers between 1 and 5

array([2.92727935, 1.93042522, 3.01596358])